var heroName = localStorage.getItem("name");
var ability = localStorage.getItem("ability");
var personality = localStorage.getItem("personality");

var profiles = {
    "Fire": {
        "Agressive": "Born in the ashes of a kingdom destroyed by war, this fierce hero harnessed the power of living flame after surviving a catastrophic inferno that should have claimed his life. Fueled by an unrelenting rage against injustice, he charges headfirst into battle, overwhelming enemies with blazing attacks and a relentless fighting style. His fiery abilities grow stronger with his emotions, turning every confrontation into a storm of heat and destruction. Though his aggressive nature often puts him at odds with allies, his courage and determination make him a powerful protector who will stop at nothing to defeat those who threaten the innocent.",
        "Supportive": "Blessed with the power of flame, this hero uses fire not as a weapon of destruction, but as a source of protection and hope. After discovering their ability to control living fire, they dedicated themselves to helping others, using warm healing flames to strengthen allies, shield the vulnerable, and light the way through even the darkest challenges. Compassionate and dependable, they stand at the heart of every team, inspiring courage and unity wherever they go. While their flames can burn fiercely when loved ones are threatened, their true strength comes from their unwavering desire to support those around them and help others rise stronger than before.",
        "Timid": "Born with the rare ability to command fire, this hero struggles with a shy and Timid nature that often keeps them in the background. Afraid of drawing attention to themselves, they rarely show the true extent of their fiery power unless others are in danger. Despite their quiet demeanor, they possess a kind heart and an unwavering sense of duty, using their flames to protect those who cannot protect themselves. Over time, each challenge helps them gain confidence, proving that true courage is not the absence of fear, but the strength to act despite it.",
        "Reluctant": "Gifted with the power to command fire, this hero never sought greatness and would much rather avoid conflict altogether. Haunted by the destruction their flames can cause, they are hesitant to embrace their abilities, often stepping forward only when there is no one else to help. Despite their reluctance, a strong sense of responsibility compels them to act when innocent lives are at stake. Through every challenge, they learn that true heroism is not about seeking glory, but about finding the courage to use their gifts for the good of others, even when they would rather walk away.",
        "Passive":"Gifted with the power to command fire, this hero possesses a calm and passive nature that stands in stark contrast to their destructive abilities. Rather than rushing into battle, they prefer to observe, avoid conflict, and seek peaceful solutions whenever possible. Their flames are most often used to provide warmth, light, and protection rather than destruction. While their laid-back attitude can sometimes be mistaken for a lack of courage, they step forward when truly needed, wielding their fire with quiet confidence. Their gentle spirit proves that even the fiercest power can be guided by patience and restraint."
    },
    "Water": {
        "Agressive": "Gifted with the power to command water, this hero wields the relentless force of oceans, rivers, and storms with fierce determination. They charge into battle without hesitation, using crashing waves, razor-sharp currents, and powerful whirlpools to overwhelm their enemies. Quick to confront threats and fiercely protective of those they care about, they believe the best defense is a strong offense. While their aggressive nature can sometimes lead them into dangerous situations, their courage and unwavering resolve make them a formidable champion whose strength is as unstoppable as the tide itself.",
        "Supportive": "Gifted with the power to command water, this hero uses the strength of rivers, tides, and rain to protect and uplift those around them. Rather than seeking glory in battle, they focus on supporting their allies, using restorative waters to soothe injuries, create defensive barriers, and guide their team through danger. Calm, dependable, and compassionate, they believe that true power lies in helping others succeed. Their steady presence and selfless nature make them a trusted companion, proving that even the gentlest currents can shape the course of great adventures.",
        "Timid": "Blessed with the power to command water, this hero is quiet, cautious, and often uncertain of their own abilities. More comfortable observing from the sidelines than standing in the spotlight, they use gentle currents, soothing rain, and protective waves to help others whenever they can. Despite their Timid nature, they possess a deep well of inner strength, and when friends or innocent people are threatened, they find the courage to act. Through each challenge they face, they learn that bravery is not about being fearless, but about moving forward like a steady river, even when doubt tries to hold them back.",
        "Reluctant": "Gifted with the ability to control water, this hero never wanted the responsibility that came with such power. Preferring a quiet and simple life, they often avoid conflict and hesitate to get involved in the struggles of others. Yet when danger threatens those around them, they Reluctantly call upon rushing tides and powerful waves to defend the innocent. Though uncertain of their role as a hero, their calm nature, compassion, and hidden strength make them a dependable guardian who continually proves that courage can emerge from even the most Reluctant heart.",
        "Passive":"Gifted with the power to command water, this hero embodies the calm and steady nature of a tranquil lake. They rarely seek conflict and prefer to let events unfold naturally, believing that patience often succeeds where force fails. Using their abilities to shape currents, summon gentle waves, and create protective barriers, they focus on maintaining balance rather than dominating a fight. Though their passive nature can make them seem detached, they possess a quiet wisdom and unwavering reliability. When circumstances demand action, they move with the unstoppable force of a rising tide, proving that even the calmest waters hold immense strength beneath the surface."
    },
    "Lightning": {
        "Agressive": "Gifted with the power to command lightning, this hero thrives in the heat of battle and meets every challenge head-on. Their ability to unleash crackling bolts, electrify the ground beneath their foes, and move with incredible speed makes them a terrifying force on the battlefield. Driven by a fierce determination to defeat evil, they rarely back down from a fight and often charge into danger before others have time to react. While their aggressive nature can sometimes lead to reckless decisions, their courage and unwavering resolve make them a powerful champion who strikes as swiftly and fiercely as the storm itself.",
        "Supportive": "Gifted with the power to command lightning, this hero uses their abilities to protect and empower those around them rather than seek personal glory. They can channel electric energy to enhance their allies' speed, create protective fields of crackling energy, and illuminate even the darkest paths. Always ready to lend a helping hand, they believe that teamwork is the key to overcoming any challenge. Their positive attitude and unwavering support inspire others to push beyond their limits, making them the spark that brings a team together when hope seems lost.",
        "Timid": "Blessed with the power to command lightning, this hero often struggles with self-doubt and prefers to avoid attention whenever possible. Though capable of summoning powerful bolts, crackling shields, and bursts of incredible speed, they are cautious about using their abilities and worry about the harm they might cause. Their Timid nature makes them hesitant to step forward, but when others are in danger, they find the courage to act despite their fears. With every challenge they overcome, they learn that true bravery is not being fearless, but choosing to stand up for others even when their heart is racing like a storm.",
        "Reluctant": "Gifted with the power to command lightning, this hero never wanted to be seen as a champion or a warrior. The destructive force of their abilities makes them wary of using them, and they often avoid situations that could draw attention or place others at risk. However, when danger strikes, they Reluctantly step forward, summoning crackling bolts and surges of electricity to protect those in need. Though they constantly question whether they are suited to the role of a hero, their sense of responsibility and quiet determination prove that even the most Reluctant individuals can become a beacon of hope when it matters most.",
        "Passive": "Gifted with the power to command lightning, this hero possesses a calm and passive nature that contrasts sharply with the raw energy they wield. Rather than seeking battle or attention, they prefer to remain on the sidelines, observing situations carefully before acting. Their electrical abilities are often used to illuminate dark paths, power essential equipment, or create protective barriers rather than attack opponents. While they rarely take the lead, their steady judgment and quiet reliability make them a trusted ally. When the situation demands it, they can unleash the full force of a storm, proving that even the most reserved individuals can possess extraordinary power."
    },
    "Nature": {
        "Agressive": "Gifted with the power to command nature, this hero is a fierce defender of the wild and those under their protection. They wield twisting vines, thorn-covered roots, and the raw strength of the earth to overwhelm anyone who threatens the balance of the natural world. Quick to act and unafraid of confrontation, they charge into battle with unwavering determination, letting nature's fury answer every attack. Though their aggressive approach can sometimes create tension among allies, their passion and loyalty are undeniable, making them a powerful guardian who fights relentlessly for what they believe in.",
        "Supportive": "Gifted with the power to command nature, this hero uses their abilities to nurture, protect, and strengthen those around them. Drawing energy from the forests, rivers, and wildlife they are deeply connected to, they can summon protective vines, encourage rapid plant growth, and create safe havens for allies in times of need. Compassionate and dependable, they believe that true strength comes from helping others flourish rather than seeking personal glory. Their calm presence and unwavering support make them the heart of any team, proving that the greatest heroes are often those who help others grow.",
        "Timid": "Blessed with the ability to command nature, this hero possesses a deep connection to forests, plants, and wildlife, but lacks the confidence to stand in the spotlight. Quiet and Timid, they often doubt their own strength, preferring to hide among the trees rather than confront danger directly. When faced with threats to the innocent or the natural world, however, they summon the courage to act, calling upon twisting vines, protective roots, and the resilience of the earth itself. Though fear is a constant companion, their kindness and determination prove that even the gentlest soul can become a true hero when it matters most.",
        "Reluctant": "Gifted with the power to command nature itself, this hero never wanted to bear the responsibility that came with their abilities. Finding peace among forests and wild places, they prefer the quiet company of plants and animals over the expectations of others. Yet when nature or innocent lives are threatened, they Reluctantly call upon twisting vines, towering roots, and the strength of the earth to defend those in need. Though hesitant to step into the spotlight, their deep compassion and connection to the natural world make them a steadfast protector who proves that even the most Reluctant heroes can become a force for good.",
        "Passive": "Gifted with the power to command nature, this hero prefers harmony over conflict and rarely seeks to impose their will on others. Deeply connected to forests, rivers, and wildlife, they spend much of their time observing and learning from the natural world. Their abilities allow them to summon protective vines, encourage plants to flourish, and calm even the most chaotic environments. Though passive by nature and hesitant to engage in battle, they possess a quiet resilience that emerges when others are in need. Like nature itself, they are patient, enduring, and capable of great strength when the balance they cherish is threatened."
    },
}

if(!(heroName )){
    alert("Hero Profile is missing");
    window.location = "index.html"
}else{
    document.querySelectorAll('#hero-name').forEach(element => {
        element.innerHTML = heroName
    });
    document.getElementById("ability").classList += " "+ ability.toLocaleLowerCase();
    document.getElementById("hero-ability").innerText = ability;
    document.getElementById("hero-bio").innerText = profiles[ability][personality];
    document.getElementById("hero-personality").innerText = personality;
}
